### ISSUE TITLE
Cannot access response data

### ISSUE THREAD

**Issue by sdclibbery** [dovahcrow/bitmex-rs#2]
Hi, I'm probably being dozy (I'm quite new to rust), but it seems that it's impossible to access any of the returned data.

For example, if I get the user wallet data:

`let wallet = rt.block_on(bm.get_user_wallet(GetUserWalletRequest { ..Default::default() }).unwrap()).expect("Failed to get wallet");`

Then I can't actually access any of the fields on the returned wallet; eg `wallet.amount` gives a compile error `error[E0616]: field 'amount' of struct 'bitmex::model::definitions::Wallet' is private`.

Is there a way to access this data?

**Comment by dovahcrow** [comment]
@sdclibbery Yea that's true I forgot to export some (actually a lot!) fields. I've fixed that in the 0.1.7 version
