### ISSUE TITLE
Market order creation error

### ISSUE THREAD

**Issue by algoeng** [dovahcrow/bitmex-rs#20]
About an hour ago, I got the following error on a simple Market order (one order but sent via PostOrderBulkRequest). Note that this code worked fine before and works fine now, but this just happened randomly, meaning the response of the server was malformed somehow, for a brief time I guess. My logic retried the order multiple times for 3 seconds before giving up. All retries ended with the same error. I am just starting to use this crate and new to Rust in general. I was wondering if this has been seen before, and if so, is there a way to prevent it from happening?

Err=reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) }

**Comment by dovahcrow** [comment]
Hi @kr011 , thanks for your bug report! May I ask if you can turn on the backtrace by setting `RUST_BACKTRACE=1` and also `RUST_LOG=bitmex=error` in the environment and use the git version of `bitmex-rs` to run your program in the debug mode? I guess the error happens here: https://github.com/dovahcrow/bitmex-rs/blob/master/src/rest/client.rs#L116 but I need confirmation.

**Comment by algoeng** [comment]
Hi @dovahcrow. Unfortunately I can't repro the issue. And it hasn't happened since. I am using the latest release, "0.2.2". If you guys haven't seen this issue, then it maybe it was a one time thing hopefully, and we can close this.

**Comment by dovahcrow** [comment]
@kr011 sure. You are always welcomed to reopen this issue anytime.
