### ISSUE TITLE
Hitting unreachable in websocket's parse_message (version 0.2.2)

### ISSUE THREAD

**Issue by algoeng** [dovahcrow/bitmex-rs#21]
Apparently hitting unreachable!() in parse_message of websocket is possible. Last night I had the following panic:

`thread '<unnamed>' panicked at 'internal error: entered unreachable code', /home/kr/.cargo/registry/src/github.com-1ecc6299db9ec823/bitmex-0.2.2/src/websocket.rs:102:14`

This was in a long running session. I am not sure what they sent.

**Comment by dovahcrow** [comment]
Hi @kr011 the issue was fixed in 44548a31. I'll release a new version soon.

**Comment by algoeng** [comment]
Thank you.

**Comment by dovahcrow** [comment]
@kr011 maybe you can first have a try on the master branch. I want to include tokio 1.0 in the new release however it is blocked by hyper-tls https://github.com/hyperium/hyper-tls/issues/76.

**Comment by algoeng** [comment]
@dovahcrow what's in master doesn't seem to be usable yet. I get this as soon as I start it.
```
itMEXWsMessage::Info: InfoMessage { info: "Welcome to the BitMEX Realtime API.", version: 2020-12-16T22:50:54Z, timestamp: 2020-12-27T19:34:11.742Z, docs: "https://www.bitmex.com/app/wsAPI", limit: Limit { remaining: 35 } }
thread '<unnamed>' panicked at 'internal error: entered unreachable code: Cannot deserialize message from BitMEX: '{"success":true,"request":{"args":["***",***,"***"],"op":"authKeyExpires"}}'', /home/kr/.cargo/git/checkouts/bitmex-rs-2861a3a714a639fb/af8602e/src/websocket/mod.rs:123:27
```
Looks like the response to the WS Auth message. I just copy/pasted from the examples:
```
let expires = (Utc::now() + Duration::seconds(30)).timestamp();
ws_client.send(Command::authenticate(expires as u64)).await?;
```

**Comment by dovahcrow** [comment]
@kr011 I pushed a new fix. You can have a try to see if that solves the issue.

**Comment by algoeng** [comment]
@dovahcrow that fixed it. Thanks. I am running it now. I will let you know if I run into any bugs. Cheers!

**Comment by dovahcrow** [comment]
@kr011 Glad to hear that!
