### ISSUE TITLE
Swagger-Editor Error

### ISSUE THREAD

**Issue by Js-sz** [dovahcrow/bitmex-rs#4]
![Swagger-Editor](https://user-images.githubusercontent.com/49776812/60310359-1c89be00-9985-11e9-9ee0-6a2ed25e4b01.png)

**Comment by dovahcrow** [comment]
Hi @Js-sz did you mean the swagger.json file in this repo contains errors?

**Comment by Js-sz** [comment]
it doesn't matter, i export swagger.json from bitmex, it contains errors too;

**Comment by Js-sz** [comment]
are you chinese?

**Comment by dovahcrow** [comment]
> it doesn't matter, i export swagger.json from bitmex, it contains errors too;

Do you think there's anything I can do in this library?

**Comment by Js-sz** [comment]
if you know trade，you can do something about quant strategy.
or you can put  binance-async-rs(spot) ，biemex-rs(future) , deribit-rs(option) together.

**Comment by Js-sz** [comment]
or do this .
![AwesomeScreenshot-Bitcoin-Futures-and-Options-Exchange-Bitcoin-Derivatives-Trading-Deribit-Indexes-2019-07-03-17-07-14](https://user-images.githubusercontent.com/49776812/60579905-a2a76980-9db6-11e9-8a0c-1df5849a0c95.png)

**Comment by Js-sz** [comment]
or do like this : https://github.com/nntaoli-project/GoEx
rust is very safe and efficient.so it is very proper and promising

**Comment by dovahcrow** [comment]
@Js-sz I think a universal and multi-platform trading library is not the scope of this project.
