### ISSUE TITLE
using shadowsocks proxy，can‘t connect to the bitmex

### ISSUE THREAD

**Issue by Js-sz** [dovahcrow/bitmex-rs#6]
using shadowsocks proxy，can‘t connect to the bitmex

**Comment by dovahcrow** [comment]
bitmex-rs doesn't care about any proxy settings like HTTP_PROXY env. If you'd like to have that feature, it would be better to set your proxy on the network interface level, e.g. utun.

**Comment by dovahcrow** [comment]
Ok, I think the proxy feature may also be useful for US developers. Please checkout the [proxy example](https://github.com/dovahcrow/bitmex-rs/blob/master/examples/proxy.rs).

**Comment by dovahcrow** [comment]
Close the issue due to inactivity.
